// GENERATED by scripts/ci/sync_versions.py from platform/versions.json.
// Do not edit by hand — see platform/VERSIONING.md.
//
// The web app versions INDEPENDENTLY of the Android app (VERSIONING.md D1), so
// this is web.finance's own line, not apps.finance's.
export const APP_VERSION = "0.1.0";
