build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 7
  TooManyFunctions:
    thresholdInFiles: 12
    thresholdInClasses: 12

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140
